[
  {
    "player": "Donk",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 38.5,
    "recent_results": [42.0, 40.0, 44.0, 41.0],
    "season_projection": 41.5,
    "matchup_projection": 42.0,
    "role_projection": 41.0,
    "pace_volume_projection": 1.05,
    "market_baseline_uncertainty": 1.2,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "cairne",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 16.5,
    "recent_results": [12.0, 13.0, 11.0, 14.0],
    "season_projection": 12.5,
    "matchup_projection": 12.0,
    "role_projection": 12.2,
    "pace_volume_projection": 0.92,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  },
  {
    "player": "xKacpersky",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 30.5,
    "recent_results": [25.0, 26.0, 24.0, 27.0],
    "season_projection": 25.5,
    "matchup_projection": 25.0,
    "role_projection": 25.2,
    "pace_volume_projection": 0.94,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.54
  },
  {
    "player": "xKacpersky (HS)",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 16.5,
    "recent_results": [12.0, 11.0, 13.0, 12.0],
    "season_projection": 12.0,
    "matchup_projection": 11.8,
    "role_projection": 12.1,
    "pace_volume_projection": 0.93,
    "market_baseline_uncertainty": 0.7,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  },
  {
    "player": "NiKo",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 28.5,
    "recent_results": [32.0, 31.0, 33.0, 30.0],
    "season_projection": 31.5,
    "matchup_projection": 32.0,
    "role_projection": 31.0,
    "pace_volume_projection": 1.04,
    "market_baseline_uncertainty": 1.1,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "Donk (Low Line)",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 24.5,
    "recent_results": [28.0, 27.0, 29.0, 26.0],
    "season_projection": 27.5,
    "matchup_projection": 28.0,
    "role_projection": 27.2,
    "pace_volume_projection": 1.02,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "mazay",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 18.5,
    "recent_results": [14.0, 15.0, 13.0, 14.0],
    "season_projection": 14.2,
    "matchup_projection": 14.0,
    "role_projection": 14.1,
    "pace_volume_projection": 0.92,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  },
  {
    "player": "Matheos",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 19.5,
    "recent_results": [15.0, 14.0, 16.0, 15.0],
    "season_projection": 15.0,
    "matchup_projection": 14.8,
    "role_projection": 15.1,
    "pace_volume_projection": 0.93,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  },
  {
    "player": "sh1ro",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 32.0,
    "recent_results": [36.0, 35.0, 37.0, 36.0],
    "season_projection": 36.0,
    "matchup_projection": 36.5,
    "role_projection": 35.8,
    "pace_volume_projection": 1.06,
    "market_baseline_uncertainty": 1.1,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "mizu",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 31.5,
    "recent_results": [27.0, 26.0, 28.0, 27.0],
    "season_projection": 27.2,
    "matchup_projection": 27.0,
    "role_projection": 27.1,
    "pace_volume_projection": 0.94,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.54
  },
  {
    "player": "mazay (Kills)",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 30.5,
    "recent_results": [26.0, 25.0, 27.0, 26.0],
    "season_projection": 26.0,
    "matchup_projection": 25.8,
    "role_projection": 26.1,
    "pace_volume_projection": 0.95,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.54
  },
  {
    "player": "zont1x",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 25.5,
    "recent_results": [29.0, 30.0, 28.0, 29.0],
    "season_projection": 29.0,
    "matchup_projection": 29.2,
    "role_projection": 28.9,
    "pace_volume_projection": 1.03,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "leakz",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 17.5,
    "recent_results": [13.0, 14.0, 12.0, 13.0],
    "season_projection": 13.1,
    "matchup_projection": 13.0,
    "role_projection": 13.2,
    "pace_volume_projection": 0.92,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  },
  {
    "player": "m0NESY",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 35.5,
    "recent_results": [40.0, 39.0, 41.0, 39.0],
    "season_projection": 39.5,
    "matchup_projection": 40.0,
    "role_projection": 39.2,
    "pace_volume_projection": 1.07,
    "market_baseline_uncertainty": 1.1,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "NiKo (Headshots)",
    "sport": "CS2",
    "stat": "Maps 1-2 Headshots",
    "line": 15.5,
    "recent_results": [19.0, 18.0, 20.0, 19.0],
    "season_projection": 19.0,
    "matchup_projection": 19.2,
    "role_projection": 18.9,
    "pace_volume_projection": 1.05,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.52
  },
  {
    "player": "frontales",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 31.0,
    "recent_results": [26.0, 27.0, 25.0, 26.0],
    "season_projection": 26.0,
    "matchup_projection": 25.8,
    "role_projection": 26.1,
    "pace_volume_projection": 0.94,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.54
  },
  {
    "player": "podi",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 28.5,
    "recent_results": [32.0, 31.0, 33.0, 32.0],
    "season_projection": 32.0,
    "matchup_projection": 32.2,
    "role_projection": 31.9,
    "pace_volume_projection": 1.04,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "sjuush",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 28.5,
    "recent_results": [32.0, 33.0, 31.0, 32.0],
    "season_projection": 32.0,
    "matchup_projection": 32.1,
    "role_projection": 31.9,
    "pace_volume_projection": 1.04,
    "market_baseline_uncertainty": 1.0,
    "sport_variance_factor": 1.1,
    "estimated_market_probability": 0.52
  },
  {
    "player": "grape",
    "sport": "CS2",
    "stat": "Map 1 Headshots",
    "line": 7.5,
    "recent_results": [10.0, 9.0, 11.0, 10.0],
    "season_projection": 10.0,
    "matchup_projection": 10.2,
    "role_projection": 9.9,
    "pace_volume_projection": 1.05,
    "market_baseline_uncertainty": 0.6,
    "sport_variance_factor": 0.9,
    "estimated_market_probability": 0.52
  },
  {
    "player": "jackasmo",
    "sport": "CS2",
    "stat": "Maps 1-2 Kills",
    "line": 19.5,
    "recent_results": [15.0, 16.0, 14.0, 15.0],
    "season_projection": 15.0,
    "matchup_projection": 14.8,
    "role_projection": 15.1,
    "pace_volume_projection": 0.92,
    "market_baseline_uncertainty": 0.8,
    "sport_variance_factor": 1.0,
    "estimated_market_probability": 0.53
  }
]
